
# Simformer Training Configuration

# note: yaml can't resolve 1e-3 as 0.001, so write float numbers explicitly

task_name: two_moons

strategy:
  method: "flow"
  model: "flux"

optimizer:
  patience: 10
  cooldown: 2
  factor: 0.5
  accumulation_size: 100
  rtol: 1.0e-4
  max_lr: 1.0e-3
  min_lr: 1.0e-8

model:
  in_channels: 1
  vec_in_dim: null
  context_in_dim: 1
  mlp_ratio: 4
  qkv_multiplier: 1
  num_heads: 4
  depth: 8
  depth_single_blocks: 16
  axes_dim: [10]
  qkv_bias: true
  theta: 40
  params_dtype: "float32"

training:
  batch_size: 4096
  nsteps: 50000
  ema_decay: 0.99
  multistep: 1
  early_stopping: true
  val_every: 100
  experiment_id: 1
  restore_model: true
  train_model: false