
# Simformer Training Configuration

# note: yaml can't resolve 1e-3 as 0.001, so write float numbers explicitly

task_name: slcp


optimizer:
  patience: 10
  cooldown: 2
  factor: 0.5
  accumulation_size: 100
  rtol: 1.3e-4
  max_lr: 1.0e-3
  min_lr: 1.0e-7

model:
  dim_value: 40
  dim_id: 40
  dim_condition: 10
  fourier_features: 128
  num_heads: 4
  num_layers: 8
  widening_factor: 3
  qkv_features: null
  num_hidden_layers: 1

training:
  batch_size: 4000
  nsteps: 10000
  nepochs: 10
  multistep: 1
  early_stopping: true
  print_every: 100
  experiment_id: 1
  restore_model: false
  train_model: true

  total_number_steps_scaling: 3
  max_number_steps: 100000
  min_number_steps: 5000
