# Flux Training Configuration

# note: yaml can't resolve 1e-3 as 0.001, so write float numbers explicitly

task_name: slcp

optimizer:
  patience: 5
  cooldown: 2
  factor: 0.5
  accumulation_size: 50
  rtol: 1.0e-2
  max_lr: 5.0e-4
  min_lr: 1.0e-6

model:
  in_channels: 1
  vec_in_dim: null
  context_in_dim: 1
  mlp_ratio: 4
  qkv_multiplier: 1
  num_heads: 6
  depth: 8
  depth_single_blocks: 16
  axes_dim: [20]
  use_rope: false
  qkv_bias: true
  theta: 20
  param_dtype: float32

training:
  batch_size: 8192
  nsteps: 10000
  nepochs: 3
  multistep: 1
  early_stopping: true
  print_every: 50
  experiment_id: 1
  restore_model: false
  train_model: true
  val_every: 50
  val_error_ratio: 1.1
  cmax: 5
  step_size: 0.01
