
# Simformer Training Configuration

# note: yaml can't resolve 1e-3 as 0.001, so write float numbers explicitly

task_name: two_moons

strategy:
  method: "flow"
  model: "simformer"

optimizer:
  patience: 10
  cooldown: 2
  factor: 0.5
  accumulation_size: 100
  rtol: 1.0e-4
  max_lr: 1.0e-3
  min_lr: 1.0e-8

model:
  dim_value: 40
  dim_id: 40
  dim_condition: 10
  fourier_features: 128
  num_heads: 6
  num_layers: 8
  widening_factor: 3
  qkv_features: 60
  num_hidden_layers: 1

training:
  batch_size: 4096
  nsteps: 50000
  ema_decay: 0.999
  multistep: 1
  early_stopping: true
  val_every: 100
  experiment_id: 3
  restore_model: false
  train_model: true